augmentation:
  background_noise:
    enabled: true
    p: 0.5
    snr_max: 10
    snr_min: 5
  band_stop_filter:
    enabled: true
    max_bandwidth_fraction: 1.99
    max_center_freq: 4000
    min_bandwidth_fraction: 0.5
    min_center_freq: 200
    p: 0.4
  masking:
    enabled: true
    mask_feature_length: 10
    mask_feature_prob: 0.05
    mask_time_length: 10
    mask_time_prob: 0.1
  pitch_shift:
    enabled: true
    max_semitones: 3
    min_semitones: -4
    p: 0.414561434758
  time_stretch:
    enabled: true
    max_rate: 1.2
    min_rate: 0.8
    p: 0.7832338213626
  white_noise:
    enabled: false
cv:
  holdout: true
  n_folds: 5
  splitter:
    _partial_: true
    _target_: src.preprocessing.data_split.group_child_id_split
    n_splits: 5
data:
  audio_folder: data/audio
  audio_processed_folder: data/audio_processed
  remove_bad_data: false
  removed_utterances_jsonl: data/removed_utterance_ids_fold1.jsonl
  test_jsonl: data/utterance_metadata.jsonl
  train_jsonl: data/train_phon_transcripts.jsonl
  train_jsonl_darpa: data/train_phon_transcripts_darpa_timit.jsonl
  train_jsonl_speechocean: data/train_phon_transcripts_speechocean.jsonl
  train_jsonl_talkbank: data/train_phon_transcripts_talkbank.jsonl
  train_jsonl_ultrasuite: data/train_phon_transcripts_ultrasuite.jsonl
  train_on_all_data: true
  word_train_jsonl: data/train_word_transcripts.jsonl
  word_train_jsonl_talkbank: data/train_word_transcripts_talkbank.jsonl
debug: false
device: cuda:0
ema:
  decay: 0.999
  enabled: true
  update_after_step: 100
  update_every: 1
logging:
  project_name: smac_ssl_sweep_v2
  save_dir: outputs
  save_val_logits_best: true
  use_random_name: true
  use_wandb: true
  wandb_entity: speech-phonetic-track
loss:
  _target_: src.utils.loss.FocalCTCLoss
  alpha: null
  gamma: 0.2135779965701
model:
  _target_: src.utils.models.Wav2Vec2CTC
  LLA: false
  age_head_lambda: 0.1
  augmentation:
    background_noise:
      enabled: true
      p: 0.5
      snr_max: 10
      snr_min: 5
    band_stop_filter:
      enabled: true
      max_bandwidth_fraction: 1.99
      max_center_freq: 4000
      min_bandwidth_fraction: 0.5
      min_center_freq: 200
      p: 0.4
    masking:
      enabled: true
      mask_feature_length: 10
      mask_feature_prob: 0.05
      mask_time_length: 10
      mask_time_prob: 0.1
    pitch_shift:
      enabled: true
      max_semitones: 3
      min_semitones: -4
      p: 0.414561434758
    time_stretch:
      enabled: true
      max_rate: 1.2
      min_rate: 0.8
      p: 0.7832338213626
    white_noise:
      enabled: false
  backbone_lr: 3.27679772e-05
  classifier_dropout: 0.029476046524
  decoder:
    _target_: src.utils.decoder.GreedyDecoder
  enable_age_head: true
  gradient_checkpointing: false
  head_lr: 0.0007637745179
  lora_alpha: 64
  lora_dropout: 0.0708234944101
  lora_r: 16
  pretrained_name: microsoft/wavlm-large
  use_lora: false
mtl:
  alternate_batches: true
  enabled: false
  word_tokenizer:
    _target_: src.preprocessing.word_char_tokenizer.WordCharTokenizer
preprocessing:
  max_duration_sec: 50
  min_duration_sec: 0.22
  sample_rate: 16000
  sound_dimension: mono
pretraining:
  enabled: false
  groups:
  - jsonl_paths:
    - data/train_phon_transcripts_speechocean.jsonl
    - data/train_phon_transcripts_darpa_timit.jsonl
    name: less_similar_external
  - jsonl_paths:
    - data/train_phon_transcripts_ultrasuite.jsonl
    name: similar_external
  num_epochs: 2
sampler:
  train:
    _target_: src.preprocessing.dataset.DurationBatchSampler
    bucket_size: 100
    drop_last: false
    max_batch_seconds: 30
    shuffle: true
  val:
    _target_: src.preprocessing.dataset.DurationBatchSampler
    bucket_size: 100
    drop_last: false
    max_batch_seconds: 40
    shuffle: false
scheduler:
  backbone:
    _target_: src.utils.tri_stage_lr_scheduler.TriStageLRScheduler
    final_lr_scale: 0.01
    init_lr_scale: 0.01
    lr: 3.27679772e-05
    phase_ratio:
    - 0.044
    - 0.392
    - 0.564
  head:
    _target_: src.utils.tri_stage_lr_scheduler.TriStageLRScheduler
    final_lr_scale: 0.01
    init_lr_scale: 0.01
    lr: 0.0007637745179
    phase_ratio:
    - 0.0141
    - 0.4164
    - 0.5695
ssl_init:
  backbone_subdir: backbone_pretrained
  enabled: false
  pretrained_name: null
  run_dir: null
tokenizer:
  _target_: src.preprocessing.phoneme_tokenizer.PhonemeTokenizer
training:
  backbone_lr: 3.27679772e-05
  dataloader:
    num_workers: 4
    pin_memory: true
    prefetch_factor: 4
  early_stopping_patience: 3
  freeze_backbone_epochs: 1
  gradient_checkpointing: false
  guard_PER: 0.29
  guard_epochs: 3
  head_lr: 0.0007637745179
  lla_lr: 0.01
  max_grad_norm: 10
  mixed_precision: true
  num_epochs: 12
  optimizer:
    _target_: torch.optim.AdamW
  weight_decay: 2.38061058e-05
