_target_: src.utils.models_mtl.Wav2Vec2MTL
pretrained_name: microsoft/wavlm-base-plus
classifier_dropout: 0.2635076763481
augmentation: ${augmentation}
backbone_lr: ${training.backbone_lr}
head_lr: ${training.head_lr}
gradient_checkpointing: ${training.gradient_checkpointing}
LLA: true
