model_name_or_path: "qwen/Qwen3-ASR-1.7B"
output_dir: "output/qwen_exp025/"
train_audio_encoder: true
train_projector: false
prompt: "Transcribe only the children's voice."
max_epochs: 3
per_device_train_batch_size: 4
eval_batch_size: 8
gradient_accumulation_steps: 4
gradient_checkpointing: true
precision: "bf16"
eval_steps: 5000
save_steps: 5000
save_total_limit: 10
load_best_model_at_end: false
metric_for_best_model: "loss"
dataloader_num_workers: 4
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.0
  target_modules:
    [
      "q_proj",
      "k_proj",
      "v_proj",
      "o_proj",
      "gate_proj",
      "up_proj",
      "down_proj",
    ]
data:
  train_sources:
    - csv: "input/csrc-processed-input/train_pred_parakeet_exp013.csv"
      audio_dir: "input/csrc-processed-input/audio"
      wer_threshold:
        "3-4": null
        "5-7": null
        "8-11": null
    - csv: "input/csrc-processed-talkbank/train_pred_parakeet_exp013.csv"
      audio_dir: "input/csrc-processed-talkbank/audio"
      max_text_len: 200
      max_duration_sec: 30.0
      wer_threshold:
        "3-4": null
        "5-7": null
        "8-11": null
        "12+": null
        "unknown": null
  train_manifest: "output/qwen_exp025/train_manifest.json"
  val_manifest: "input/csrc-smoke/val_manifest.json"
  max_duration_sec: 30.0
augment:
  spec_augment:
    freq_masks: 1
    freq_width: 15
    time_masks: 1
    time_width: 0.05
    prob:
      train: 0.5
      talkbank: 0.2
  speed_perturb: null
optim:
  lr: 1e-4
  weight_decay: 0.01
  optim_name: "adamw_torch"
scheduler:
  name: "linear"
  warmup_ratio: 0.1
wandb:
  enabled: true
  project: csrc
  name: qwen_exp025
